<?xml version="1.0" encoding="UTF-8"?>
<!--
  cleanup.xsl — silkpage XSL transform: cleanup.xml → cleanup.html
  Extends the silkpage core XSL chain.

  Input:  src/xml/en/cleanup.xml  (static page structure)
          report/cleanup.xml       (scan data, included at build time)
  Output: output/cleanup.html      (served by Nginx / cdn.example.org)

  CDN asset URLs use the @cdn@ token, replaced by silkpage build params.
-->
<xsl:stylesheet
    xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
    xmlns:html="http://www.w3.org/1999/xhtml"
    version="1.0">

  <!-- ── Import silkpage core chain ──────────────────────────────────────── -->
  <xsl:import href="http://silkpage.markupware.com/release/core/current/src/xsl/ala/chunk.xsl"/>
  <xsl:import href="param.xsl"/>

  <xsl:output method="html" encoding="UTF-8" indent="yes" doctype-public="-//W3C//DTD HTML 5//EN"/>

  <!-- ── Parameters ────────────────────────────────────────────────────────  -->
  <xsl:param name="cdn"         select="'//cdn.example.org'"/>
  <xsl:param name="api.url"     select="'/api/report'"/>
  <xsl:param name="report.xml"  select="'report/cleanup.xml'"/>

  <!-- ── Page template ─────────────────────────────────────────────────────  -->
  <xsl:template match="webpage[@id='cleanup-report']">
    <html lang="en">
      <head>
        <meta charset="UTF-8"/>
        <meta name="viewport" content="width=device-width, initial-scale=1"/>
        <title><xsl:value-of select="head/title"/></title>
        <!-- CDN-hosted stylesheet (Nginx maps cdn.example.org) -->
        <link rel="stylesheet" href="{$cdn}/assets/css/cleanup.css"/>
      </head>
      <body class="cleanup-report">
        <header>
          <h1>Disk Space Cleanup Report</h1>
          <p class="meta" id="scan-meta">Loading…</p>
        </header>

        <main>
          <!-- ── Section: summary ──────────────────────────────────────────── -->
          <xsl:apply-templates select="section[@id='summary']"/>

          <!-- ── Section: live table (populated by JS from /api/report) ───── -->
          <section id="items">
            <h2>Reclaimable Items</h2>
            <div id="total-banner" class="total-banner" hidden="hidden"></div>
            <table id="cleanup-table" class="cleanup-table">
              <thead>
                <tr>
                  <th>Size</th>
                  <th>Label</th>
                  <th>Path</th>
                  <th>Risk</th>
                  <th>singine Command</th>
                </tr>
              </thead>
              <tbody id="cleanup-tbody">
                <!-- Populated by fetch-report.js at runtime -->
                <!-- Static fallback: items from cleanup.xml include (below) -->
                <xsl:apply-templates select="document($report.xml)/cleanup-report/item"/>
              </tbody>
            </table>
          </section>

          <!-- ── Section: how-to ───────────────────────────────────────────── -->
          <xsl:apply-templates select="section[@id='howto']"/>
        </main>

        <footer>
          <p>
            Generated by
            <a href="{$cdn}/docs/cleanup">singine cleanup</a> ·
            served via <a href="//cdn.example.org">cdn.example.org</a>
          </p>
        </footer>

        <!-- CDN-hosted JS (dynamic report refresh) -->
        <script src="{$cdn}/assets/js/cleanup.js" defer="defer"></script>
        <!-- Inline config so JS knows where to fetch -->
        <script>window.CLEANUP_API = '<xsl:value-of select="$api.url"/>';</script>
      </body>
    </html>
  </xsl:template>

  <!-- ── Static item row (from report/cleanup.xml) ─────────────────────── -->
  <xsl:template match="cleanup-report/item">
    <tr class="item risk-{@risk}" data-id="{@id}">
      <td class="size"><xsl:value-of select="@size"/></td>
      <td class="label"><xsl:value-of select="@label"/></td>
      <td class="path"><code><xsl:value-of select="@path"/></code></td>
      <td class="risk badge-{@risk}"><xsl:value-of select="@risk"/></td>
      <td class="cmd">
        <code class="singine-cmd"><xsl:value-of select="singine-cmd"/></code>
        <button class="copy-btn" aria-label="Copy singine command">Copy</button>
        <details class="cmd-detail">
          <summary>shell / win</summary>
          <code class="shell-cmd"><xsl:value-of select="shell-cmd"/></code>
          <code class="win-cmd"><xsl:value-of select="win-cmd"/></code>
        </details>
      </td>
    </tr>
  </xsl:template>

  <!-- ── Passthrough: standard silkpage sections ─────────────────────────── -->
  <xsl:template match="section">
    <section id="{@id}">
      <h2><xsl:value-of select="title"/></h2>
      <xsl:apply-templates select="*[not(self::title)]"/>
    </section>
  </xsl:template>

  <xsl:template match="para">
    <p><xsl:apply-templates/></p>
  </xsl:template>

  <xsl:template match="note">
    <aside class="note"><xsl:apply-templates/></aside>
  </xsl:template>

  <xsl:template match="orderedlist">
    <ol><xsl:apply-templates select="listitem"/></ol>
  </xsl:template>

  <xsl:template match="listitem">
    <li><xsl:apply-templates/></li>
  </xsl:template>

  <xsl:template match="programlisting">
    <pre><code><xsl:value-of select="."/></code></pre>
  </xsl:template>

  <xsl:template match="code">
    <code><xsl:apply-templates/></code>
  </xsl:template>

  <xsl:template match="emphasis">
    <em><xsl:apply-templates/></em>
  </xsl:template>

</xsl:stylesheet>
