import json
import tempfile
import unittest
from io import StringIO
from pathlib import Path
from unittest.mock import patch

from singine.command import main


class RealmCommandsTest(unittest.TestCase):
    def _run(self, *args):
        stdout = StringIO()
        stderr = StringIO()
        with patch("sys.stdout", stdout), patch("sys.stderr", stderr):
            code = main(list(args))
        return code, stdout.getvalue(), stderr.getvalue()

    def _mock_run_command(self, command, timeout=20):
        command_key = " ".join(command)
        if command[:2] == ["nslookup", "lutino.io"]:
            return {
                "ok": True,
                "command": list(command),
                "exit_code": 0,
                "stdout": "Server: 127.0.0.1\nName: lutino.io\nAddress: 127.0.0.1",
                "stderr": "",
            }
        if command[:2] == ["whois", "lutino.io"]:
            return {
                "ok": True,
                "command": list(command),
                "exit_code": 0,
                "stdout": "Domain Name: LUTINO.IO\nRegistrar: TEST-REGISTRAR",
                "stderr": "",
            }
        if command[:4] == ["openssl", "s_client", "-connect", "lutino.io:443"]:
            return {
                "ok": True,
                "command": list(command),
                "exit_code": 0,
                "stdout": "CONNECTION ESTABLISHED\nProtocol version: TLSv1.3\nVerification: OK",
                "stderr": "",
            }
        return {
            "ok": False,
            "command": list(command),
            "error": f"unexpected-command:{command_key}",
        }

    def _render_html_report(self, report_dir: Path, payloads):
        report_dir.mkdir(parents=True, exist_ok=True)
        rows = []
        for title, payload in payloads:
            pretty = json.dumps(payload, indent=2)
            rows.append(
                "<section>"
                f"<h2>{title}</h2>"
                f"<pre>{pretty}</pre>"
                "</section>"
            )
        html = (
            "<!doctype html>"
            "<html><head><meta charset='utf-8'>"
            "<title>Singine Realm Test Report</title>"
            "<style>"
            "body{font-family:Menlo,Consolas,monospace;background:#f6f3ea;color:#1f2933;margin:2rem;}"
            "h1,h2{font-family:Georgia,serif;color:#7c2d12;}"
            "section{background:#fffdf8;border:1px solid #d6d3d1;padding:1rem;margin:1rem 0;box-shadow:0 1px 3px rgba(0,0,0,.08);}"
            "pre{white-space:pre-wrap;word-break:break-word;background:#faf7f2;padding:1rem;border:1px solid #e7e5e4;}"
            "a{color:#9a3412;}"
            "</style></head><body>"
            "<h1>Singine Realm Test Report</h1>"
            "<p>Generated by <code>py.tests.test_realm_commands</code>.</p>"
            + "".join(rows)
            + "</body></html>"
        )
        (report_dir / "index.html").write_text(html, encoding="utf-8")

    def test_realm_commands_generate_visual_report(self):
        report_dir = Path("/tmp/singine-realm-visual")
        if report_dir.exists():
            for path in sorted(report_dir.rglob("*"), reverse=True):
                if path.is_file():
                    path.unlink()
                elif path.is_dir():
                    path.rmdir()

        with tempfile.TemporaryDirectory() as tmpdir:
            output_dir = Path(tmpdir) / "realm"
            with patch("singine.realm_ops._run_command", side_effect=self._mock_run_command):
                check_code, check_stdout, check_stderr = self._run(
                    "realm",
                    "check",
                    "--realm",
                    "local.realm",
                    "--domain",
                    "lutino.io",
                    "--service",
                    "dns",
                    "--service",
                    "tls",
                    "--output-dir",
                    str(output_dir),
                    "--json",
                )
                self.assertEqual(check_code, 0, check_stderr)
                check_payload = json.loads(check_stdout)

                cron_code, cron_stdout, cron_stderr = self._run(
                    "realm",
                    "cron-write",
                    "--cron",
                    "*/30 * * * *",
                    "--realm",
                    "local.realm",
                    "--domain",
                    "lutino.io",
                    "--service",
                    "dns",
                    "--service",
                    "tls",
                    "--output-dir",
                    str(output_dir),
                    "--json",
                )
                self.assertEqual(cron_code, 0, cron_stderr)
                cron_payload = json.loads(cron_stdout)

                broadcast_code, broadcast_stdout, broadcast_stderr = self._run(
                    "realm",
                    "broadcast-interest",
                    "--topic",
                    "realm dns tls trust vault",
                    "--output-dir",
                    str(output_dir),
                    "--json",
                )
                self.assertEqual(broadcast_code, 0, broadcast_stderr)
                broadcast_payload = json.loads(broadcast_stdout)

                read_code, read_stdout, read_stderr = self._run(
                    "realm",
                    "read-atom",
                    check_payload["response_path"],
                    "--json",
                )
                self.assertEqual(read_code, 0, read_stderr)
                read_payload = json.loads(read_stdout)

            self.assertTrue(Path(check_payload["response_path"]).exists())
            self.assertTrue(Path(cron_payload["cron_file"]).exists())
            self.assertTrue(Path(broadcast_payload["response_path"]).exists())
            self.assertEqual(read_payload["services"]["dns"], 2)
            self.assertEqual(read_payload["services"]["tls"], 2)

            self._render_html_report(
                report_dir,
                [
                    ("realm check", check_payload),
                    ("realm read-atom", read_payload),
                    ("realm cron-write", cron_payload),
                    ("realm broadcast-interest", broadcast_payload),
                    (
                        "generated files",
                        {
                            "request_atom": check_payload["request_path"],
                            "response_atom": check_payload["response_path"],
                            "cron_file": cron_payload["cron_file"],
                            "broadcast_atom": broadcast_payload["response_path"],
                        },
                    ),
                ],
            )


if __name__ == "__main__":
    unittest.main()
