package singine.activity;

import java.util.Map;

/**
 * Outcome — measured result of a completed {@link Action}.
 *
 * Every Outcome carries the three components of the platform's
 * ultimate metric:
 *
 * <pre>
 *   usage_cost_benefit_score = usage_value + business_value - platform_cost
 * </pre>
 *
 * This formula is the primary optimisation target across all domains.
 * Outcomes that cannot supply numeric values for all three components
 * are considered incomplete.
 *
 * Collibra alignment
 * ──────────────────
 * Outcomes map to Collibra Metric assets.  The
 * {@code collibraId} field in {@link #getMeasurements()} (key
 * {@code :collibra/id}) should be populated when a Collibra link exists.
 *
 * PROV-O alignment
 * ────────────────
 * An Outcome is a {@code prov:Entity} generated by the {@link Action}
 * ({@code prov:Activity}) following the {@link Policy} ({@code prov:Plan}).
 */
public interface Outcome {

    // ── Identity ──────────────────────────────────────────────────

    /** Stable identifier — matches the EDN :outcome/id key. */
    String getId();

    // ── Provenance ────────────────────────────────────────────────

    /** The action that produced this outcome. */
    Action getAction();

    /** Classification of the result quality. */
    OutcomeType getType();

    // ── Measurements ──────────────────────────────────────────────

    /**
     * All measurements collected during the action.
     * Keys are namespaced EDN keywords represented as strings,
     * e.g. {@code ":metric/usage-volume"}, {@code ":collibra/id"}.
     */
    Map<String, Object> getMeasurements();

    // ── Ultimate metric components ────────────────────────────────

    /**
     * Usage value: a dimensionless score representing adoption,
     * volume of consumption, or frequency of access.
     * Higher is better.
     */
    double getUsageValue();

    /**
     * Business value: the assessed benefit delivered to the consuming
     * business unit or process.  Expressed in the same unit as
     * {@link #getPlatformCost()}.
     */
    double getBusinessValue();

    /**
     * Platform cost: the total delivery and infrastructure cost
     * incurred to produce this outcome.
     * Lower is better.
     */
    double getPlatformCost();

    // ── Derived metric ────────────────────────────────────────────

    /**
     * The ultimate metric: usage + business value minus platform cost.
     *
     * <pre>
     *   score = usage_value + business_value - platform_cost
     * </pre>
     *
     * A positive score indicates net value creation.
     * This default implementation may be overridden for weighted variants.
     *
     * @return composite score (higher is better)
     */
    default double getUsageCostBenefitScore() {
        return getUsageValue() + getBusinessValue() - getPlatformCost();
    }

    // ── Serialisation ─────────────────────────────────────────────

    /**
     * Serialise to an XML fragment.
     *
     * <pre>{@code
     * <outcome id="..." type="SUCCESS">
     *   <ultimate-metric id="usage-cost-benefit-score">
     *     <usage-value>...</usage-value>
     *     <business-value>...</business-value>
     *     <platform-cost>...</platform-cost>
     *     <score>...</score>
     *   </ultimate-metric>
     * </outcome>
     * }</pre>
     */
    String toXml();

    /**
     * Serialise to an EDN map compatible with Logseq and Clojure queries.
     *
     * <pre>{@code
     * {:outcome/id "..."
     *  :outcome/type :SUCCESS
     *  :outcome/usage-value 0.0
     *  :outcome/business-value 0.0
     *  :outcome/platform-cost 0.0
     *  :outcome/score 0.0}
     * }</pre>
     */
    String toEdn();
}
