/**
 * Singine Activity Model — the core execution abstraction.
 *
 * <h2>Overview</h2>
 * <p>The {@code singine.activity} package defines a polyglot activity model
 * that separates <em>what should be done</em> ({@link singine.activity.Activity}),
 * <em>how it should be executed</em> ({@link singine.activity.Policy}),
 * <em>the concrete execution instance</em> ({@link singine.activity.Action}),
 * and <em>the measured result</em> ({@link singine.activity.Outcome}).</p>
 *
 * <h2>Core Interfaces</h2>
 * <ul>
 *   <li>{@link singine.activity.Activity}  — template: identity, taxonomy, policy, default context</li>
 *   <li>{@link singine.activity.Policy}    — execution algorithm: governs how an Action runs</li>
 *   <li>{@link singine.activity.Action}    — runtime instance: follows a Policy against an Activity</li>
 *   <li>{@link singine.activity.Outcome}   — measurement: usage value + business value − platform cost</li>
 *   <li>{@link singine.activity.Taxonomy}  — classification node: domain → category → subcategory</li>
 *   <li>{@link singine.activity.photo.PhotoReviewActivities} — nested photo-review activity bindings published via xmldoclet</li>
 * </ul>
 *
 * <h2>Lifecycle</h2>
 * <pre>
 *   PENDING → RUNNING → COMPLETED
 *                     ↘ FAILED
 *   PENDING → CANCELLED
 *   DEFERRED → PENDING → RUNNING
 * </pre>
 *
 * <h2>Ultimate Metric</h2>
 * <p>Every {@link singine.activity.Outcome} carries three cost-benefit components:</p>
 * <pre>
 *   usage_cost_benefit_score = usage_value + business_value - platform_cost
 * </pre>
 * <p>This formula is the primary optimization target across all domains
 * (elia-electricity, data-production, filesystem-operations, etc.).</p>
 *
 * <h2>Taxonomy Canonical Source</h2>
 * <p>The single source of truth is
 * {@code core/resources/singine/activity/taxonomy.edn}.
 * From this EDN file, the following artifacts are generated:</p>
 * <ul>
 *   <li>XML domain model</li>
 *   <li>LaTeX documentation</li>
 *   <li>SVG diagrams (DP(DP) logo)</li>
 *   <li>HTML pages (SilkPage: sina.khakbaz.com/docs/activity/)</li>
 *   <li>GraphQL query templates</li>
 *   <li>SPARQL query templates</li>
 *   <li>Logseq Clojure queries</li>
 * </ul>
 *
 * <h2>Collibra Alignment</h2>
 * <table border="1">
 *   <tr><th>Collibra Concept</th><th>singine.activity Equivalent</th></tr>
 *   <tr><td>Asset Type</td><td>Activity (taxonomy.domain/category)</td></tr>
 *   <tr><td>Business Rule</td><td>Policy (SBVR enforcement level)</td></tr>
 *   <tr><td>Metric</td><td>Outcome (usage_cost_benefit_score)</td></tr>
 *   <tr><td>Status Workflow</td><td>ActivityStatus enum</td></tr>
 *   <tr><td>Responsibility</td><td>Policy.getDecision() + Policy.getRationale()</td></tr>
 * </table>
 *
 * <h2>PROV-O Alignment</h2>
 * <ul>
 *   <li>{@code Action}   → {@code prov:Activity}</li>
 *   <li>{@code Outcome}  → {@code prov:Entity} generated by the Action</li>
 *   <li>{@code Policy}   → {@code prov:Plan} followed by the Action</li>
 *   <li>{@code Activity} → {@code prov:Plan} template</li>
 * </ul>
 *
 * <h2>Polyglot Note</h2>
 * <p>Implementations exist identically on the JVM (Java, Groovy, Clojure)
 * and via subprocess/IPC adapters in Python, Node.js, Go, and Rust.
 * Shell sourcing: each Action sources {@code ~/.singine/activity.sh} and
 * {@code ~/.singine/activity.bash} before executing, serializing its context
 * to {@code SINGINE_*} environment variables.</p>
 *
 * <h2>Inspection and Publication</h2>
 * <p>The CLI command {@code singine server inspect --json} walks this package
 * recursively so nested packages such as {@code singine.activity.photo} are
 * visible in snapshots, man pages, and generated XML publication artifacts.
 * The same package graph is published through xmldoclet and
 * {@code docs/spec-publication.xml} for downstream SilkPage rendering.</p>
 *
 * @see singine.activity.Activity
 * @see singine.activity.Policy
 * @see singine.activity.Action
 * @see singine.activity.Outcome
 * @see singine.activity.Taxonomy
 * @see singine.activity.ActivityTemplate
 * @see singine.activity.BaseAction
 * @see singine.activity.BaseOutcome
 */
package singine.activity;
